# Generated by Django 3.2.12 on 2022-02-28 20:16

from decimal import Decimal
from django.db import migrations, models
import mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=60)),
                ('picture', models.ImageField(upload_to='product_pics/')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4)),
                ('availability', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, mixins.UpdateMixin),
        ),
    ]
