# Generated by Django 3.2.12 on 2022-02-28 19:29

from django.db import migrations, models
import django.db.models.deletion
import mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('identification', models.CharField(max_length=11)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, mixins.UpdateMixin),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.person')),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('people.person',),
        ),
    ]
