# Generated by Django 3.2.12 on 2022-03-01 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='person',
            name='identification',
            field=models.CharField(max_length=25),
        ),
    ]
