# Generated by Django 3.2.12 on 2022-03-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20220301_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='person',
            name='identification',
            field=models.CharField(max_length=35),
        ),
    ]
