# Generated by Django 3.2.12 on 2022-02-28 21:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('taken', models.BooleanField(default=False)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.client')),
                ('products', models.ManyToManyField(to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.DecimalField(decimal_places=2, max_digits=7)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quotes.quote')),
            ],
        ),
    ]
