# Generated by Django 3.2.12 on 2022-03-01 02:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7),
        ),
    ]
