# Generated by Django 3.2.12 on 2022-03-01 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('quotes', '0002_auto_20220301_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quotes.quote')),
            ],
        ),
        migrations.RemoveField(
            model_name='quote',
            name='products'
        ),
        migrations.AddField(
            model_name='quote',
            name='products',
            field=models.ManyToManyField(through='quotes.ProductQuote', to='products.Product'),
        ),
    ]
